server:
  port: 10091

eureka:
  client:
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
    preferIpAddress: true

spring:
  application:
    name: movie-info-service