server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    leaseRenewalIntervalInSeconds: 1
    preferIpAddress: true
    appname: eureka-discovery-server

spring:
  application:
    name: eureka-discovery-server